environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '12'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install --global packages/cli

test_script:
  - node --version
  - npm --version
  - npm test

cache:
  - node_modules
  - '%APPDATA%\npm-cache'

build: off
