os: linux
dist: bionic
language: node_js
node_js:
  - 10
  - 12
before_script:
  - node --version
  - npm --version
  - npm install
  - npm install --global packages/cli
script:
  - npm test
cache:
  directories:
  - node_modules
addons:
  firefox: latest-esr
  chrome: stable
