# Work-around for https://github.com/travis-ci/travis-ci/issues/8836
sudo: true
language: node_js
node_js:
  - 10
  - 12
before_script:
  - node --version
  - npm --version
  - npm install
  - npm install --global packages/cli
script:
  - npm test
os:
  - linux
cache:
  directories:
  - node_modules
addons:
  firefox: latest
  chrome: stable
