version: 2

nvm: &nvm
  name: Setup NVM
  command: |
    curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash -s -- --no-use
    echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
    echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
    echo 'nvm install $NODE_VERSION' >> $BASH_ENV
    echo 'nvm alias default $NODE_VERSION' >> $BASH_ENV

jobs:
  node10:
    macos:
      xcode: "11.2.0"
    environment:
      NODE_VERSION: "10"
    steps:
      - checkout
      - run: *nvm
      - run: brew cask install firefox google-chrome
      - run: node --version
      - run: npm --version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm install --global packages/cli
      - run: npm test
  node12:
    macos:
      xcode: "11.2.0"
    environment:
      NODE_VERSION: "12"
    steps:
      - checkout
      - run: *nvm
      - run: brew cask install firefox google-chrome
      - run: node --version
      - run: npm --version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm install --global packages/cli
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - node10
      - node12
